### ISSUE TITLE
.profile (and thus IA_USER & IA_PASS) does not seem to be evaluated when running romweasel through menu

### ISSUE THREAD

**Issue by Ulugbeg** [Koston-0xDEADBEEF/MiSTer-ROMweasel#8]
### Observed behavior:

- Added `IA_USER` & `IA_PASS` to `.profile`
- Rebooted
- ran `romweasel` through the `Scripts` menu
- tried to download a gb game.

### Result:
- a file in the cache folder with the correct name, but it's content is a webpage explaining the resource isn't available

### Expected result:
- a successful download.

### Digging in:

Doing the same over SSH _does_ successfully get the file.

When running `romweasel` over SSH, I see it successfully login to IA (the dialog opens). 

When running it through the `Scripts` menu, I don't see that same dialog open.

Using SSH to see what is running when `romweasel` is run through the menu, it seems to be started through a file `/tmp/script`

relevant output from `ps`:

```
1140 root     {script} /bin/bash /tmp/script -f root
1142 root     {romweasel.sh} /bin/zsh /media/fat/Scripts/romweasel.sh
1158 root     /bin/dialog --title MiSTer ROMweasel v0.9.13 --cancel-label Quit --help-button --help-tags --help-status --default-item 0 --extra-button --extra-label Info --help-
```

`/tmp/script`'s contents:

```#!/bin/bash
export LC_ALL=en_US.UTF-8
export HOME=/root
cd $(dirname /media/fat/Scripts/romweasel.sh)
/media/fat/Scripts/romweasel.sh
echo "Press any key to continue"
```

Therefor, I assume `/root/.profile` is not read, and thus the variables aren't set when this is executed through the `Scripts` menu, resulting in download failures.

**Comment by Ulugbeg** [comment]
I added the following lines near the top of `romweasel.sh` and that resolved it for me. Do you want a pull request for it?

```
if [ -f ~/.profile ]; then 
    . ~/.profile;
fi
```

**Comment by Koston-0xDEADBEEF** [comment]
Thanks for reporting! I must've missed this in testing when adding the login feature.

I adopted your fix and pushed it, `update_all` should catch the new version if you've added the json to downloader config.
